on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ajaxerpacr.azurecr.io
        username: ${{ secrets.acr_ajaxerpacr_username }}
        password: ${{ secrets.acr_ajaxerpacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ajaxerpacr.azurecr.io/ajaxakscluster:${{ github.sha }}
        docker push ajaxerpacr.azurecr.io/ajaxakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ajaxakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ajaxakscluster1f4b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ajaxakscluster1f4b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ajaxakscluster1f4b
        container-registry-url: ajaxerpacr.azurecr.io
        container-registry-username: ${{ secrets.acr_ajaxerpacr_username }}
        container-registry-password: ${{ secrets.acr_ajaxerpacr_password }}
        secret-name: ajaxaksclustdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: ajaxakscluster1f4b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ajaxerpacr.azurecr.io/ajaxakscluster:${{ github.sha }}
        imagepullsecrets: |
          ajaxaksclustdockerauth